### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by merytouceda** [functional-dark-side/agnostos-wf#13]
Hi! 

I am going through the installation process following AGNOSTOS_usage.md. I was changing the configuration files and I got to the database directory path changes. I assumed that in order to know that path I first need to do the following step: 

_"4. Check that you have the required external DBs listed in the [config.yaml](https://github.com/functional-dark-side/agnostos-wf/blob/master/db_update/config/config.yaml) file (under "Databases"). In case you miss some of them, you can find the instructions for the download in the script [download_DBs.sh](https://github.com/functional-dark-side/agnostos-wf/blob/master/download_DBs.sh). If you want to download all needed databases simply run sh download_DBs.sh (be patient this may take a while...)."_

So I have gone ahead and done the downloading before I change the configuration files. If this is the correct thing to do I wanted to suggest you mention it in the readme before the change in configuration step, for clarity. 

Thanks!

**Comment by ChiaraVanni** [comment]
Hi @merytouceda!
Thank you for pointing this out. I reordered the points in the AGNOSTOS_usage file.
Best,

Chiara
