### ISSUE TITLE
majority_vote_categ.R fails; Error in dirname(opt$contig)

### ISSUE THREAD

**Issue by jarrodscott** [functional-dark-side/agnostos-wf#5]
Hello. 

I am following the tutorial on [Integrating AGNOSTOS gene categories into anvi'o projects](https://merenlab.org/2021/05/28/agnostos/#import-agnostos-into-an-anvio) using the example data from the tutorial. I believe I have followed the recipe correctly yet at the step where the workflow calls `majority_vote_categ.R` I get the following error:

```
Error in dirname(opt$contig) : a character vector argument expected
``` 

I looked at the script but I am afraid it was not obvious why it was failing. I tried several times to reinstall everything but no luck. I also tried different versions of R (3.6, 4.0). I am stuck :)

Any help would be appreciated. I also attached the log file [job_AGNOSTOS.log](https://github.com/functional-dark-side/agnostos-wf/files/6718164/job_AGNOSTOS.log). 

Here is how I am running the command:

```
MMSEQ="/home/scottjj/miniconda3/envs/mmseqs2/bin"

agnostos-wf/Profile_search/profile_search.sh \
                       --query infant_gut_genes.fasta \
                       --clu_hmm IGD_agnostos/GC_profiles/clu_hmm_db \
                       --clu_cat IGD_agnostos/cluster_ids_categ.tsv \
                       --threads 10 --mmseqs $MMSEQ/mmseqs
```

**Comment by genomewalker** [comment]
Hi @jarrodscott 

indeed it seems there is a problem [here](https://github.com/functional-dark-side/agnostos-wf/blob/master/Profile_search/majority_vote_categ.R#L71) where the script expects an argument and is not provided.

@ChiaraVanni can you fix it?

**Comment by genomewalker** [comment]
@jarrodscott As a temporary solution, I believe that you can comment or remove this [line](https://github.com/functional-dark-side/agnostos-wf/blob/master/Profile_search/majority_vote_categ.R#L71) from the file `majority_vote_categ.R`

**Comment by jarrodscott** [comment]
thanks @genomewalker !

I commented out that line and then just ran the `majority_vote_categ.R` R script and while the original error is gone I now get the following:

```
Joining, by = "gene"
Adding missing grouping variables: `gene`
Error in fread(opt$info, stringsAsFactors = F, header = T) :
  Input is empty or only contains BOM or terminal control characters
Calls: %>% -> setNames -> fread
Execution halted
```

I am going to restart the entire workflow and see if this error pops up again or not. Thanks for your quick reply :)

**Comment by genomewalker** [comment]
Looks like it is missing the argument `--info` in the tutorial, I would wait for @ChiaraVanni to double-check the tutorial, sorry for this.

**Comment by ChiaraVanni** [comment]
Hi @jarrodscott! Sorry for this! I made a mistake in changing the contig information table from mandatory to optional. The problem should be fixed now. 
Let me know if you encounter other problems.

**Comment by jarrodscott** [comment]
Thanks @ChiaraVanni ! I am testing the workflow from the tutorial now. I will report back when it is finished :)

**Comment by jarrodscott** [comment]
Hello @ChiaraVanni I reran the workflow and it finished without error. However, I do not believe it output all of the files listed [here](https://github.com/functional-dark-side/agnostos-wf/blob/master/Output_README.md#profile-search). I am attaching the log file for the job and the `ls -l` results from the `profile_search_res` directory. I am happy to open this as a separate issue. Thank you again!

[profile_search_res_dir.txt](https://github.com/functional-dark-side/agnostos-wf/files/6733465/profile_search_res_dir.txt)
[job_AGNOSTOS.log](https://github.com/functional-dark-side/agnostos-wf/files/6733466/job_AGNOSTOS.log)

**Comment by ChiaraVanni** [comment]
Hi @jarrodscott, the two "summary" files are produced only when you provide an extra file with the gene to contig correspondence. I will add this to the output description file.
Thank you for the feedback!

**Comment by jarrodscott** [comment]
Ah! Thanks @ChiaraVanni 

Just to be clear, from the [anvio tutorial](https://merenlab.org/2021/05/28/agnostos/) I would run the command like this and add the extra file with the `--info` flag? Is this the `infant_gut_gene_calls.tsv` file generated by `anvi-export-gene-calls`? 

```
Profile_search/profile_search.sh --query infant_gut_genes.fasta \
			         --clu_hmm IGD_agnostos/GC_profiles/clu_hmm_db \
			         --clu_cat IGD_agnostos/cluster_ids_categ.tsv \
			         --threads 10
                                 --info ???
```

Thank you for your patience :)

**Comment by ChiaraVanni** [comment]
Yes, you need the first two columns of that file (gene-contig). But, I just modify the script `majority_vote_categ.R` so you can pass directly the full file `infant_gut_gene_calls.tsv`.
I will add this to the tutorial as well later.
Thank you!

**Comment by jarrodscott** [comment]
Brilliant! I am rerunning now with the updated scripts. Thank you!!

**Comment by jarrodscott** [comment]
Hi @ChiaraVanni 

Just wanted to pass along the results of the test I ran on the `profile_search.sh` workflow. Hopefully these data look correct. The zip file contains a log file plus the following:

-- `infant_gut_genes_vs_mg_gtdb_hmm_search_res_best-hits.tsv`
-- `infant_gut_genes_vs_mg_gtdb_hmm_search_res_summary-categ.tsv`
-- `infant_gut_genes_vs_mg_gtdb_hmm_search_res_summary-classes.tsv`

[AGNOSTOS_TEST.zip](https://github.com/functional-dark-side/agnostos-wf/files/6741127/AGNOSTOS_TEST.zip)

This issue can be closed if everything looks ok :)

**Comment by ChiaraVanni** [comment]
Hi @jarrodscott! 
The files are fine!
Thank you again for the feedback!
