### ISSUE TITLE
db_creation snakemake command: conda download/install stage stuck

### ISSUE THREAD

**Issue by mhyleung** [functional-dark-side/agnostos-wf#8]
Dear all

I am new to snakemake, but it seems like my db_creation snakemake command is stuck in the conda stage:

```
$ snakemake -s Snakefile --use-conda -j 100 --cluster-config config/cluster.yaml --cluster "sbatch --export=ALL -t 48 -c 1 --ntasks-per-node 1 --nodes 1 --cpus-per-task 1 --job-name hostname.0001" -R --until workflow_report

Migrating .snakemake folder to new format...
Migration complete
Building DAG of jobs...
Removing incomplete Conda environment [path]/agnostos-wf/envs/workflow.yml...
Creating conda environment [path]/agnostos-wf/envs/workflow.yml...
Downloading and installing remote packages.
```

This has been here for over 15 hours now.

I am not sure if it is because of the number of tasks/nodes/cpus I have set, but I am not sure if this is supposed to take this long. Thanks

Marcus

**Comment by ChiaraVanni** [comment]
Hi Marcus,

I think this is a problem related to conda. It happened to me once and I was able to solve it this way:
First, kill your snakemake command, start a new terminal, and get rid of the conda environment snakemake was trying to create with

`conda env remove -p path/to/your-environment`

Then the following steps:

```
conda config --remove channels conda-forge
conda config --add channels conda-forge
```

After this try to run snakemake again.

Let us know if this works

Chiara

**Comment by mhyleung** [comment]
Hi Chiara

Thank you for your quick response. Sorry this might sound stupid, but how do I know which environment snakemake is trying to create? 

Thanks

M

**Comment by ChiaraVanni** [comment]
If you type  `conda env list` you should see the environment. Should be something like

`/.../agnostos-wf/db_creation/.snakemake/conda/<number>`

Chiara

**Comment by mhyleung** [comment]
Ok so I do not see a conda environment being created by snakemake. Could it be that I set up AGNOSTOS in the following steps:

1) Created a blank conda environment named it agnostos
2) Activated this environment and followed the installation_script.sh to set up the non-conda packages
3) Downloaded the databases using the download_DB.sh script
4) Went to the workflow.yml link and installed the conda packages manually
5) Started Snakemake

If this is the problem, then I should first remove the agnostos conda environment that I have manually created right?

**Comment by ChiaraVanni** [comment]
Yes I would do so. However, I think you can also specify the conda environment you created manually in the configuration file `config/config.yaml`, modifying this line `conda_env: "/vol/cloud/agnostos-wf/envs/workflow.yml"`.  But I never tried this before.

**Comment by mhyleung** [comment]
I shall remove the conda env first and try snakemake again. Thanks!

M

**Comment by mhyleung** [comment]
So I have performed the instructed steps, and ran snakemake again. Although it has been only 20 minutes or so, I should be able to see the new environment being created if i type `conda env list` ? I still do not see it for now...hmm

**Comment by mhyleung** [comment]
Hi Chiara and everyone

Sorry for the repeated messages, so I woke up today and after about 15hrs or so, the conda environment appears to have been created via snakemake *yay*  

I have another error about slurm which I think I can sort out internally with my labmates (i think it's a internal cluster problem that we have, so no worries).

I just want to know now that the environment is set by snakemake, a subsequent run in the future will be using the same environment right? I just want to know if next time I run db_update it will need to generate a new conda environment again...

Thanks

Marcus

**Comment by ChiaraVanni** [comment]
Hi Marcus,
yes, snakemake is going to use the created environment in the future runs. Unfortunately, at the moment if you run `db_update` it will create a new environment. I'm implementing a better solution for this. I will let you know when I have the updates ready. 

Chiara

**Comment by mhyleung** [comment]
Thank you very much. I shall close this thread now :)
