### ISSUE TITLE
profile_search.sh output question

### ISSUE THREAD

**Issue by mhyleung** [functional-dark-side/agnostos-wf#9]
Dear all

Just want to take this opportunity here to say thank you for creating this promising tool, and the help I have been receiving here on github :)

I managed to run profile_search.sh on a fasta file of 34,234 coding sequences. However, the resulting file [my_sample]_vs_mg_gtdb_hmm_search_res_best-hits.tsv only contains a header and 14,925 lines of results. My understanding is that all coding sequences should be accounted for? Maybe I am missing something?

Thank you very much

Marcus

**Comment by ChiaraVanni** [comment]
Hi Marcus,
the output file of the `profile_search` contains only the query sequences that were found homologous to our gene cluster profiles based on the search parameters.
Thank you for your feedback!
Chiara

**Comment by mhyleung** [comment]
Thanks Chiara for the clarification

So then those that cannot be matched to the gene cluster profiles, should they be classified along with "environmental unknowns"? I am thinking from a analytical point of view. If I want to use this output information to describe the breakdown of my genes based on the four known/unknown categories as you have elegantly described on the manuscript, then I am just thinking what would this set of "unclassified by profile_search" collection of coding sequences belong to...

**Comment by ChiaraVanni** [comment]
The set of unclassified would need further processing. The fact that they were not found in our gene cluster database does not make them necessarily "environmental unknowns". It simply means that those sequences are not found in our DB. You could run agnostos `db_creation` on them, or search them against protein databases, such as UniProtKB, and see what you get. 
You can use MMseqs2 for a fast search (see here https://github.com/soedinglab/MMseqs2/wiki#downloading-databases and https://github.com/soedinglab/MMseqs2/wiki#searching).

**Comment by mhyleung** [comment]
Thank you!
